### ISSUE TITLE
TODO - Referencial teórico

### ISSUE THREAD

**Issue by tramasoli** [tramasoli/funphys#1]
Necessária leitura e notas do referencial teórico para texto descritivo do projeto.
- [ ] Construtivismo - Jean Piaget
- [ ] Zona do desenvolvimento proximal - Lev Vygotsky
- [ ] Aprendizagem significativa - David Ausubel
- [ ] Marco Antônio Moreira - UFRGS
